"""知识文档加载、确定性分块、重复检测和Embedding生成能力。"""

from app.knowledge.chunking import DocumentChunk, HeadingDocumentChunker
from app.knowledge.citations import build_citations
from app.knowledge.embeddings import (
    ChunkEmbedding,
    EmbeddingBatchGenerator,
    EmbeddingConfig,
    EmbeddingErrorCode,
    EmbeddingGeneration,
    EmbeddingIndexDescriptor,
    EmbeddingProvider,
    EmbeddingProviderError,
    OpenAICompatibleEmbeddingProvider,
    QueryEmbedding,
)
from app.knowledge.hybrid import (
    HybridSearchValidationError,
    RetrievalResult,
    fuse_hybrid_results,
)
from app.knowledge.loaders import (
    DocumentFormat,
    DocumentLoader,
    DocumentLoaderRegistry,
    DocumentLoadError,
    LoadedDocument,
    MarkdownDocumentLoader,
    PlainTextDocumentLoader,
    UnsupportedDocumentFormatError,
    normalize_document_content,
)
from app.knowledge.pipeline import (
    DocumentProcessingPipeline,
    DuplicateDocumentDetector,
    DuplicateDocumentError,
    ProcessedDocument,
)
from app.knowledge.reranking import (
    RerankCandidate,
    RerankDegradationReason,
    RerankedResult,
    Reranker,
    RerankExecutionError,
    RerankOutcome,
    RerankRequest,
    RerankResponse,
    RerankScore,
    RerankValidationError,
    rerank_retrieval_results,
)
from app.knowledge.retrieval import (
    KnowledgeRetrievalPipeline,
    KnowledgeRetriever,
    KnowledgeSearchChannels,
    QueryEmbeddingGenerator,
)
from app.knowledge.search import (
    KeywordQuery,
    KeywordQueryError,
    KeywordSearchHit,
    VectorSearchHit,
    build_search_document,
    preprocess_keyword_query,
)
from app.schemas.knowledge import EMBEDDING_DIMENSION, KnowledgeSearchFilter

__all__ = [
    "EMBEDDING_DIMENSION",
    "ChunkEmbedding",
    "DocumentChunk",
    "DocumentFormat",
    "DocumentLoadError",
    "DocumentLoader",
    "DocumentLoaderRegistry",
    "DocumentProcessingPipeline",
    "DuplicateDocumentDetector",
    "DuplicateDocumentError",
    "EmbeddingBatchGenerator",
    "EmbeddingConfig",
    "EmbeddingErrorCode",
    "EmbeddingGeneration",
    "EmbeddingIndexDescriptor",
    "EmbeddingProvider",
    "EmbeddingProviderError",
    "HeadingDocumentChunker",
    "HybridSearchValidationError",
    "KeywordQuery",
    "KeywordQueryError",
    "KeywordSearchHit",
    "KnowledgeRetrievalPipeline",
    "KnowledgeRetriever",
    "KnowledgeSearchChannels",
    "KnowledgeSearchFilter",
    "LoadedDocument",
    "MarkdownDocumentLoader",
    "OpenAICompatibleEmbeddingProvider",
    "PlainTextDocumentLoader",
    "ProcessedDocument",
    "QueryEmbedding",
    "QueryEmbeddingGenerator",
    "RerankCandidate",
    "RerankDegradationReason",
    "RerankExecutionError",
    "RerankOutcome",
    "RerankRequest",
    "RerankResponse",
    "RerankScore",
    "RerankValidationError",
    "RerankedResult",
    "Reranker",
    "RetrievalResult",
    "UnsupportedDocumentFormatError",
    "VectorSearchHit",
    "build_citations",
    "build_search_document",
    "fuse_hybrid_results",
    "normalize_document_content",
    "preprocess_keyword_query",
    "rerank_retrieval_results",
]
